export const FeatureCategories = {
  transportation: [
    'highway',
    'elevated highway',
    'elevated tracks',
    'toll',
    'intersections',
    'railway',
    'train',
    'train station',
    'bus',
    'bus terminal',
    'parking',
    'transit hub',
    'bridge',
    'gas station',
  ],
  time: ['day', 'night', 'sunset', 'sunrise'],
  architectural: [
    'rural',
    'suburb',
    'downtown',
    'agriculture',
    'grid streets',
    'park',
    'sports',
    'modern',
  ],
  urban: ['residential', 'commercial', 'industrial'],
  natural: ['hills', 'forest', 'river', 'valley', 'lake'],
  special: ['airport', 'hotel', 'pool'],
} as const;
